// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```



class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmlcyQBACGEv4DDsgqA58SoFHyzFUCNWk',
    appId: '1:47901490813:web:55e1e71533a56a08e8fb14',
    messagingSenderId: '47901490813',
    projectId: 'bealda-6e7f1',
    authDomain: 'bealda-6e7f1.firebaseapp.com',
    storageBucket: 'bealda-6e7f1.firebasestorage.app',
    measurementId: 'G-SFRD3FF0NT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDODJiBMDsjrYqXGDKTBcVOSv5p169bsI',
    appId: '1:47901490813:android:0d2b4e67ed1b3e8be8fb14',
    messagingSenderId: '47901490813',
    projectId: 'bealda-6e7f1',
    storageBucket: 'bealda-6e7f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0iItR9NG5_DCEkbxoToNq742iPEAwsM8',
    appId: '1:47901490813:ios:c041c921fd3a1b0de8fb14',
    messagingSenderId: '47901490813',
    projectId: 'bealda-6e7f1',
    storageBucket: 'bealda-6e7f1.firebasestorage.app',
    iosBundleId: 'com.example.gioapp',
  );
}
